version: "3.9"

services:
  app:
    image: $IMAGE_TAG
    networks:
      - traefik
    environment:
      - REACT_APP_API_ENDPOINT=${REACT_APP_API_ENDPOINT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CI_PROJECT_ID}.entrypoints=websecure"
      - "traefik.http.routers.${CI_PROJECT_ID}.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${CI_PROJECT_ID}.tls=true"
      - "traefik.http.routers.${CI_PROJECT_ID}.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
