stages:
  - build
  - deploy
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
build:
  stage: build
  tags: [ build ]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  variables:
    REACT_APP_API_ENDPOINT: https://domeinbeschrijving-hboict.acc.theburo.nl
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f ./deployment/Dockerfile -t $IMAGE_TAG . --build-arg REACT_APP_API_ENDPOINT=$REACT_APP_API_ENDPOINT
    - docker push $IMAGE_TAG
  artifacts:
    paths:
      - deployment/docker-compose.yml

deploy:
  stage: deploy
  tags: [ acceptance ]
  variables:
    GIT_STRATEGY: none
    APP_HOST: ${CI_PROJECT_ID}.acc.theburo.nl
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG
    - docker compose -p $CI_PROJECT_NAME-$CI_PROJECT_ID -f ./deployment/docker-compose.yml up -d

